/* ============================================================
   CONFIGURACIÓN  —  este es el único archivo que necesitas tocar
   ============================================================ */

const CONFIG = {

  // Nombre del evento (sale arriba en la página)
  titulo: "Números de Kart 2026 ACEK",
  subtitulo: "Escoge tu número disponible",

  // URL de tu Google Apps Script (ver README.md, paso 4).
  // Si la dejas vacía, el sitio funciona en MODO DEMO (solo en tu navegador,
  // no guarda nada en el Excel y no bloquea números entre personas).
  API_URL: "https://script.google.com/macros/s/AKfycbx-OugbR18vLJfBYsVbTCfHnr13IPceUN2guC2QhvEgtAsQYAACHlaiPEqSzY1AeSs1TA/exec",

  // ----------------------------------------------------------
  // CATEGORÍAS
  // ----------------------------------------------------------
  //  nombre      -> como se ve en la página
  //  pool        -> categorías con el MISMO pool comparten numeración:
  //                 si alguien toma el 907 en Tillotson Junior, también
  //                 queda ocupado en Tillotson Senior y Heavy.
  //  desde/hasta -> rango de números de la categoría
  //  ocupados    -> número: "piloto que lo tiene".
  //
  //  PARA LIBERAR UN NÚMERO: borra su línea completa de "ocupados".
  //  PARA OCUPAR UNO A MANO: agrega una línea igual, por ejemplo
  //      342: "Martin Salom",
  // ----------------------------------------------------------
  categorias: [
    {
      nombre: "Kid Kart (4-7)",
      pool: "kid",
      desde: 1, hasta: 99,
      ocupados: {
        2: "Lina Salazar",
        8: "Mariano Quiros",
        17: "Alessandro Calvosa",
        18: "Julian De Oliva Maya",
        21: "Kruz Botero",
        25: "Santiago Solis",
        27: "RAFAEL TERAN",
      },
    },
    {
      nombre: "VLR Junior (12-15)",
      pool: "200",
      desde: 200, hasta: 299,
      ocupados: {
        201: "Alberto Rojas",
        202: "Nicolas Marin",
        205: "Emilio Bolaños",
        206: "Samuel Esteban Chaverri Gadea",
        207: "Anouk Valerio Gonzalez",
        209: "Sebastian Recinos",
        210: "Leandro Ramirez",
        211: "Chayton Rodriguez",
        212: "Makya Rodriguez",
        214: "Emilio Wong Bustamante",
        216: "Luciano Dajles",
        217: "Sofia Calderon",
        221: "Saul Cespedes",
        222: "Sebastián Delgado Quirós",
        225: "Emilio Patiño Guzman",
        227: "Rodolfo Lavin",
        235: "Andres Dumith",
        237: "reservado ADVANCED",
        241: "Jaden Spielman",
        242: "Oliver Smith A+",
        244: "Fabian Acevedo",
        247: "Diego Antonio Mejia",
        252: "Daniela Dorado Alarcon",
        255: "Carlos Andrés Valverde Blanco",
        263: "SALOMON PIRAGUA",
        265: "Caleb Esterhuizen",
        274: "Maxwell Matcha",
        285: "Daniel Miron",
        292: "Nicholas Kotowski",
        293: "John Antonio",
      },
    },
    {
      nombre: "VLR Senior",
      pool: "300",
      desde: 300, hasta: 399,
      ocupados: {
        300: "Martin Krammers",
        301: "Diego Ramos",
        302: "Daniel Sequeira",
        303: "Diego Ramos",
        305: "Bernal Valverde Carrillo",
        307: "Jean Valerio",
        308: "Raymi Guzman",
        310: "Stefano Morice Videche",
        311: "Javier Jose Mora Zuniga",
        312: "Felipe Hernandez",
        314: "Jose Hernandez",
        315: "Luis Felipe Aguilar Porras",
        316: "Charlie Fonseca",
        317: "Mauricio Hernandez",
        318: "Luciana Morales",
        319: "Emiliano Herrera",
        320: "Mathias Hernandez",
        321: "Samuel Castro",
        322: "Rafael Fabrega",
        323: "Diego Ardiles",
        324: "Edder Herrera",
        325: "Otto Knohr",
        326: "Gerardo Moreno Hovenga",
        327: "cristian velez",
        328: "Ramses Santos",
        329: "Luis Fernando Cedeño Velázquez",
        330: "OSVALDO BLANCO",
        333: "Emilio Badilla",
        334: "Camila Nieto",
        335: "Felipe Carvajal",
        336: "Jose Halphen",
        337: "Daniel Formal Martinez",
        340: "Francisco Acuña Flaque",
        342: "Martin Salom",
        343: "Evan Michelini",
        344: "Augusto Acevedo",
        345: "Luciano Sosto",
        346: "FELIPE BENITO",
        347: "Fabian Acevedo",
        348: "Juan Pablo Patiño",
        349: "Titi Castro",
        350: "MARCO LAMUGUE EMULO PENZO",
        351: "Daniel Gardella Santamaria",
        354: "Federico Rojas Hidalgo",
        355: "André Sebastian Granados Uceda",
        357: "Julian Guevara",
        362: "Manuel Troncoso",
        364: "Santiago Benito",
        367: "Lautaro Otero",
        369: "IAN LEON",
        371: "Alesandro Carboni",
        372: "Junxi Lu",
        373: "Aldo Barboza",
        375: "Nicolas Eugenin",
        376: "Tonka Maldonado",
        377: "NICOLAS RAMILA",
        380: "Tomas Camacho",
        386: "Alex Cabrera",
        387: "Jose Hernandez",
        388: "Jeronimo Coral",
        389: "Esteban Hernandez Krause",
        394: "Francesca Morice",
        397: "Gabriel Arias",
        398: "Isabella Valldeperas",
        399: "Eduardo Jardim E Silva De Carvalho Pagliaro",
      },
    },
    {
      nombre: "VLR Master",
      pool: "400",
      desde: 400, hasta: 499,
      ocupados: {
        407: "Jean Valerio",
        408: "Amadeo Quiros",
        413: "Pedro Huguet",
        414: "Daniel Mendez",
        417: "Andres Fonseca",
        418: "Danilo Ramahlo",
        419: "Pablo Vieto",
        422: "Ronald Paniagua",
        424: "Henry Nanne",
        426: "Gerardo Moreno Hovenga",
        427: "Timothy Vivian",
        429: "Jose Hernandez Guillen",
        437: "reservado ADVANCED",
        442: "Cristian Smith",
        457: "ALDO VINCENTI",
        465: "David Steven Gardella Arias",
        468: "Marco Castro",
        478: "John Knohr",
        479: "ARIEL CASTRO",
        482: "Jorge Guerra",
        496: "Luis Alvarado Vargas",
        497: "RUBEN CARRAPATOSO",
      },
    },
    {
      nombre: "Mini ROK (9-12)",
      pool: "500",
      desde: 500, hasta: 599,
      ocupados: {
        500: "Jacobo Agudelo",
        505: "Alejandro Mendoza",
        506: "Samuel Esteban Chaverri Gadea",
        508: "Luciano Albanese",
        511: "Cesar Barradas Banda",
        513: "Nicolas Palacios",
        514: "Dominic Vera Roa",
        515: "Ayrton Rene Hayes Castillo",
        519: "MAX SANTANA",
        521: "Leandro Ramirez Del Rio",
        522: "RAFAEL BUONAFINA",
        524: "Sebastian Berroa",
        526: "Leo Yankelewitz",
        528: "Nico Salazar",
        529: "Carlos Andrés Valverde Blanco",
        533: "Dutch Westbrook",
        537: "Enzo Formal Martinez",
        555: "Emilio Wong Bustamante",
        566: "SAMUEL AVILA",
        581: "Theo Grunwedl",
        588: "Matias leon",
        592: "Jack Kotowski",
        595: "EFRAIN CHICHO",
      },
    },
    {
      nombre: "Shifter",
      pool: "600",
      desde: 600, hasta: 699,
      ocupados: {
        601: "Alan Marcel Synthes",
        602: "Andres ardiles",
        607: "Jean Valerio",
        608: "Carlos Murillo Melendez",
        609: "Franco Segnini",
        610: "Oscar Teran",
        611: "Felipe Vargas",
        614: "Jose Hernandez Guillen",
        615: "Gabriel Kawer",
        616: "Charlie Fonseca",
        617: "Mauricio Hernandez",
        618: "Ricardo Maldonado",
        619: "Daniel Andre Gardella",
        623: "Diego Ardiles",
        624: "Fabregas",
        627: "Timothy Vivian",
        637: "Daniel Formal Martinez",
        657: "Andres Fonseca",
        661: "Tonka Maldonado",
        668: "Marco Castro",
        669: "Daniel Steven Gardella Arias",
        671: "Andres Valldeperas",
        677: "Daniel Parra",
        679: "Ricardo Esquivel",
        680: "José Andrés Montalto",
      },
    },
    {
      nombre: "Micro ROK (7-10)",
      pool: "700",
      desde: 700, hasta: 799,
      ocupados: {
        700: "Alejandro Mendoza",
        704: "Felipe Nanne",
        706: "Samuel Venegas",
        708: "Luciano Albanese",
        710: "Omar Rojas",
        714: "chicho inter",
        715: "Ayrton Rene Hayes Castillo",
        718: "CHICHO PANAMA",
        721: "Leandro Ramirez",
        722: "Damian Ramirez",
        726: "Leo Yankelewitz",
        737: "Enzo Formal Martinez",
        740: "Antonio Quesada",
        781: "Theo Grunwedl",
        784: "Saul Montero",
        788: "Mathias Leon",
      },
    },
    {
      nombre: "Tilly Mini (8-12)",
      pool: "800",
      desde: 800, hasta: 899,
      ocupados: {
        804: "Felipe Nanne",
        805: "ACCR VRS",
        806: "Samuel Venegas",
        807: "ACCR VRS",
        808: "Luciano Albanese",
        810: "Damian Ramirez",
        812: "Emiliano Cisneros ACCR FK",
        813: "Sebastian Berroa",
        814: "Thiago Guerrero",
        824: "Nicolas Porras",
        825: "FEDE SEQUEIRA",
        846: "Felipe Zeledón Quesada",
        867: "EMILIANO BEIRUTE",
        884: "Eliam Leiton ACCR FMV",
        888: "Emanuel Benitez ACCR VRT4",
        898: "sin nombre",
        899: "Mauricio Villafuerte ACCR VRT",
      },
    },
    {
      nombre: "Tillotson 225 Junior (12-15)",
      pool: "900",
      desde: 900, hasta: 999,
      ocupados: {
        900: "Gabriel Valverde Calderón",
        902: "Pedro Gutierrez",
        907: "Anouk Valerio Gonzalez",
        911: "Montserrat Monge Acuña",
        924: "Julian Lahmann",
        927: "Isabella Hernández",
        928: "Emil Brautigam Arguello",
        933: "Joaquin Solano",
        941: "Clemente Cuevas",
        945: "Jose Pablo Garita Zuñiga",
        948: "Wedel",
        956: "Jian Luca Pastore",
        960: "William Alfaro",
        967: "EMIX SAMANTHA SPIELMAN",
        972: "Julian Solis",
        977: "MARIANO MARIN",
        984: "Julian Serrano Araya",
        991: "Santiago Blanco",
        997: "Guto Mendez",
        998: "Santiago Navas Castro",
      },
    },
    {
      nombre: "Tillotson 225 Senior",
      pool: "900",
      desde: 900, hasta: 999,
      ocupados: {
        905: "Rafael Fabrega",
        906: "Natalia Bräutigam Arguello",
        908: "Mayra Londoño Jordán",
        915: "Keylor Gutierrez",
        921: "Ryan Nishioka",
        923: "Gabriel José Cano",
        926: "Gerardo Moreno Riboldi",
        929: "Luca Albanese",
        931: "Jayson Herrera",
        942: "Juan Esteban Botero",
        944: "Tomas Quesada",
        957: "Julian Guevara",
        959: "Esteban Calderon",
        969: "IAN LEON",
        971: "Andres Valldeperas",
        995: "Sebastian Arce Garcia",
        999: "Sebastian Montero",
      },
    },
    {
      nombre: "Tillotson 225 Heavy",
      pool: "900",
      desde: 900, hasta: 999,
      ocupados: {
        901: "Raul Auccatoma Mendoza",
        904: "Alberto Hernandez",
        909: "Guillermo Rodriguez",
        910: "otto knor",
        912: "Nicolas Otero",
        914: "Jean Valerio",
        916: "Erick Brenes Picado",
        919: "Dieter Breisig",
        920: "Mauricio Hernandez",
        925: "Pablo Mora",
        935: "Alvaro golfin Steinvorth",
        936: "David Steven Gardella Santamaria",
        939: "Jose Daniel Duarte",
        940: "Francisco Acuña",
        947: "Manuel Sandoval Montoya",
        950: "Javier Jose Mora Zuniga",
        955: "Raúl León Méndez",
        970: "Raul Heavy",
        980: "Tomas Camacho",
        987: "Andreas Veuthey González",
      },
    },
  ],
};
